name: Deploy Astro Site to GitHub Pages

on:
  # Triggers the workflow on push or pull request events for the main branch
  push:
    branches: [astro, main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js environment to run Astro
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Ensure this version is compatible with your Astro project

      # Install dependencies and build the Astro site
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Directory to publish (default output folder for Astro)
